'use strict';

const globalActions = {
    INIT: "INIT",
    POPUP_INIT: "POPUP_INIT",
    NEW_SHORTCUT: "NEW_SHORTCUT",
    OPTION_UPDATE: "OPTION_UPDATE",
    HOST_OPTION_UPDATE: "HOST_OPTION_UPDATE",
}

const contentActions = {
    OPTION_UPDATE: "OPTION_UPDATE",
    HOST_SHORTCUTS: "HOST_SHORTCUTS",
    SHORTCUT_ADDED: "SHORTCUT_ADDED",
    START_LISTENING: "START_LISTENING",
}